import React from 'react';
import Head from 'next/head'
import Header from './components/Header';
import styles from './css/home.module.css';
import Footer from './components/Footer';

export const siteTitle = 'Сэргээгдэх эрчим хүчний төв'

export default function Layout(props) {
  const { children, home } = props;

  return (
    <div className={styles.container}>
      <Head>
        <link rel="icon" href="/renergy.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:image"
          content={`https://og-image.vercel.app/${encodeURI(
            siteTitle
          )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.zeit.co%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
        />
        <meta name="og:title" content={siteTitle} />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <Header />
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}
